---
title: 'Hamilton Christmas Bird Count: Part 3'
subtitle: 'Creating a Shiny app for the Hamilton Christmas Bird Count data'
author: Sharleen
date: '2019-03-24'
slug: hamilton-christmas-bird-count-part-3
summary: Creating a Shiny app for the Hamilton Christmas Bird Count data.
categories: []
tags:
  - data analysis
  - R
  - natural history
  - ornithology
  - ecology
  - birding
  - ggplot2
  - tidyverse
  - shiny
draft: false
image:
  caption: 'Trumpeter Swan image credit: **Sharleen**'
  preview_only: false

---

# Note

This is the third part of three for this dataset. [Part 1](https://sharleenw.rbind.io/post/hamilton_cbc_part_1/hamilton-christmas-bird-count-part-1/) contains data downloading and cleaning, [Part 2](https://sharleenw.rbind.io/post/hamilton_cbc_part_2/hamilton-christmas-bird-count-part-2/) contains visualisations and Part 3 contains my Shiny app!

# Introduction

This post is to demonstrate a Shiny app I made so that people could look through the data themselves!

I was able to make this whole app very easily thanks to the wonderful tutorial found [here](https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/)!

# Data visualising using a Shiny app

Here is the link to my Shiny app: https://sharleenw.shinyapps.io/hamilton_cbc_shiny/

And here is the code I used to make the app:

```{r setup, message = FALSE, include = FALSE}

library(here)

```



And thank you to the Christmas Bird Count! The Christmas Bird Count Data was provided by [National Audubon Society](www.christmasbirdcount.org) and through the generous efforts of [Bird Studies Canada](www.bsc-eoc.org) and countless volunteers across the western hemisphere.
